kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5001"]
networking:
  apiServerAddress: "127.0.0.1"
  podSubnet: "10.241.0.0/16"
  serviceSubnet: "10.90.0.0/16"
  apiServerPort: 6443
nodes:
- role: control-plane

  extraMounts:
  
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8090
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    listenAddress: "0.0.0.0"
    hostPort: 4443
    protocol: TCP
